name: Wakatime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme-with-wakatime-stats:
    name: Update README with Wakatime stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Wakatime Stats
        uses: donendosted/wakatime-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TABLE_STYLE: 'default'
          MAX_LANGUAGES: '5'
          WAKATIME_TIME_RANGE: 'all_time'
